#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
# frozen_string_literal: true

require 'roo'

column_to_s = Hash.new { |h, k| h[k] = h[k-1].succ }
column_to_s[1] = 'A'

pattern = Regexp.new(ARGV.shift)
ARGV.each do |path|
  xlsx = Roo::Spreadsheet.open(path)
  xlsx.each_with_pagename do |name, sheet|
    sheet.each_row_streaming do |row|
      row.each do |cell|
        value = cell.value.to_s
        if pattern =~ value
          c = column_to_s[cell.coordinate.column]
          r = cell.coordinate.row
          if STDOUT.tty?
            value.gsub!(pattern) { "\e[1;4m#$&\e[m" }
          end
          puts "#{path}:#{name}:#{c}#{r}:#{value}"
        end
      end
    end
  end
end
